### ISSUE TITLE
Adding allow header makes validation fail

### ISSUE THREAD

**Issue by sandromastronardi** [cloudevents/sdk-csharp#80]
https://github.com/cloudevents/sdk-csharp/blob/b4947655872acac77013cf1d26fdd0d6e251e4f0/src/CloudNative.CloudEvents/HttpClientExtension.cs#L127

When this code is adding the Allow header I get this response:
Misused header name. Make sure request headers are used with HttpRequestMessage, response headers with HttpResponseMessage, and content headers with HttpContent objects.

It appears that you must add it to .Content.Headers.Add("Allow", "POST");
source: https://stackoverflow.com/questions/14286436/why-i-cannot-set-allow-in-http-response-header

Without this, I can't use this in an azure function in .net core 3.1
not sure if this is a bug in other versions, I assume it behaves this way in all .NET versions?

**Comment by sandromastronardi** [comment]
Great, thanks for the fix.

**Comment by jskeet** [comment]
@sandromastronardi: Please could you file a new issue, with details of what kind of validation you want to do where? (It's not directly related to this bug.)

**Comment by sandromastronardi** [comment]
Hi @jskeet,

Thanks for the quick response, but how is it not related? As i cannot find the code you changed in the releases, has the code ever been released?

**Comment by jskeet** [comment]
> Thanks for the quick response, but how is it not related?

Because one is "this code should work and doesn't" (which was fixed by #145), the other is a question of "what code should I write to validate a CloudEvent?". 

> As i cannot find the code you changed in the releases, has the code ever been released?
 
Yes, there have been multiple releases of the various CloudNative.CloudEvents packages since this issue was closed. (This change would have been in [CloudNative.CloudEvents}(https://www.nuget.org/packages/CloudNative.CloudEvents).) The [commit history](https://github.com/cloudevents/sdk-csharp/commits/main) shows all the changes, including releases.

I feel I may be missing what you're asking though...

**Comment by sandromastronardi** [comment]
Hi @jskeet ,

I did see the fix commit, but in 1.3 it was not fixed yet, and in 2.0 releases its not at all there... so I have the feeling your fix has never made it to a release?
But I'll make a new issue then, as i'm probably wrong in assuming the new version would validate an endpoint in the same way...

**Comment by sandromastronardi** [comment]
New issue: #243

**Comment by jskeet** [comment]
I think I was confused by you not being specific about what you mean by "how to do validation". Are you *specifically* interested in webhook validation, not CloudEvent validation? That information would have been really helpful. Now I have a bit more context, I'll do some digging. (As I say though,. you *can* see all the changes in the code - everything is released via GitHub actions, so if we've removed webhook validation, that'll be in the history.)

**Comment by sandromastronardi** [comment]
Ah, sorry about that, as the ticket was about the webhook validation I assumed it was clear, my bad. I didn't know about any other validation.
I have been trying to look for it have not found yet where it was removed.
